/*-
 * Copyright (c) 2016 Michael Zhilin <mizhka@gmail.com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer,
 *    without modification.
 * 2. Redistributions in binary form must reproduce at minimum a disclaimer
 *    similar to the "NO WARRANTY" disclaimer below ("Disclaimer") and any
 *    redistribution must be conditioned upon including a substantially
 *    similar Disclaimer requirement for further binary redistribution.
 *
 * NO WARRANTY
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF NONINFRINGEMENT, MERCHANTIBILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
 * IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGES.
 */

#ifndef _MIPS_BROADCOM_BGMAC_BGMACREG_H_
#define _MIPS_BROADCOM_BGMAC_BGMACREG_H_

#define	BGMAC_REG_DEVICE_CONTROL			0x000  /* 300011 */
#define	BGMAC_REG_DEVICE_STATUS				0x004  /* 4110100 */
#define	BGMAC_REG_BIST_STATUS				0x00c  /* 0 */
#define	BGMAC_REG_INTR_STATUS				0x020  /* 10 */
#define		BGMAC_REG_INTR_STATUS_ALL		0x0f01fcff
#define		BGMAC_REG_INTR_STATUS_RX		0x00010000
#define		BGMAC_REG_INTR_STATUS_TX		0x0f000000
#define		BGMAC_REG_INTR_STATUS_TX1		0x01000000
#define		BGMAC_REG_INTR_STATUS_TX2		0x02000000
#define		BGMAC_REG_INTR_STATUS_TX3		0x04000000
#define		BGMAC_REG_INTR_STATUS_TX4		0x08000000
#define		BGMAC_REG_INTR_STATUS_ERR		0x0000fc00
#define		BGMAC_REG_INTR_STATUS_ERR_OVER		0x00004000
#define		BGMAC_REG_INTR_STATUS_ERR_DESC		0x00000400
#define		BGMAC_REG_INTR_STATUS_MDIO		0x00000010
#define		BGMAC_REG_INTR_STATUS_BITS		\
	"\020\001MRO\002MTO\003TFD\004LS\005MDIO\006MR\007MT\010TO\021RX\031TXA\032TXB\033TXC\034TXD\013EDESC\014EDATA\015EPROTO\016ERXUND\017ERXOVER\020ETXOVER"

enum bgmac_intr_status
{
	I_ERR = 1,
	I_RX = 2,
	I_TX = 4,
	I_OR = 8
};

#define	BGMAC_REG_INTERRUPT_MASK			0x024  //0
#define	BGMAC_REG_GP_TIMER				0x028  //0

#define	BGMAC_REG_INTR_RECV_LAZY			0x100
#define 	BGMAC_REG_INTR_RECV_LAZY_FC_SHIFT	24

#define	BGMAC_FLOW_CTL_THRESH				0x104

#define	BGMAC_REG_PHY_ACCESS				0x180
#define		BGMAC_REG_PHY_ACCESS_DATA  		0x0000ffff
#define		BGMAC_REG_PHY_ACCESS_ADDR		0x001f0000
#define		BGMAC_REG_PHY_ACCESS_ADDR_SHIFT		16
#define		BGMAC_REG_PHY_ACCESS_REG		0x1f000000
#define		BGMAC_REG_PHY_ACCESS_REG_SHIFT		24
#define		BGMAC_REG_PHY_ACCESS_WRITE		0x20000000
#define		BGMAC_REG_PHY_ACCESS_START		0x40000000

#define	BGMAC_REG_PHY_CONTROL				0x188
#define		BGMAC_REG_PHY_CONTROL_ADDR			0x0000001f
#define		BGMAC_REG_PHY_CONTROL_MTE			0x00800000

#define	BGMAC_REG_TXQ_CTL				0x18c
#define		BGMAC_TXQ_CTL_DBT_MASK			0x00000fff
#define		BGMAC_TXQ_CTL_DBT_SHIFT			0
#define	BGMAC_REG_RXQ_CTL				0x190
#define		BGMAC_RXQ_CTL_DBT_MASK			0x00000fff
#define		BGMAC_RXQ_CTL_DBT_SHIFT			0
#define		BGMAC_RXQ_CTL_PTE			0x00001000
#define		BGMAC_RXQ_CTL_MDP_MASK			0x3f000000
#define		BGMAC_RXQ_CTL_MDP_SHIFT			24

#define	BGMAC_REG_DMA_RX_BASE				0x220
#define	BGMAC_REG_DMA_RX_CTRL				0x220
#define		BGMAC_REG_DMA_RX_CTRL_ENABLE		0x00000001
#define		BGMAC_REG_DMA_RX_CTRL_FRAMEOFFSET	0x000000FE
#define		BGMAC_REG_DMA_RX_CTRL_PIOMODE		0x00000100
/* Separate RX Header Descriptor Enable */
#define		BGMAC_REG_DMA_RX_CTRL_SRXHDENABLE	0x00000200
#define		BGMAC_REG_DMA_RX_CTRL_OVERFLOW_CONT	0x00000400
#define		BGMAC_REG_DMA_RX_CTRL_DISABLE_PARITYCHK	0x00000800
#define		BGMAC_REG_DMA_RX_CTRL_ADDR_EXTENSION	0x00030000

#define	BGMAC_REG_DMA_RX_INDEX				0x224
#define	BGMAC_REG_DMA_RX_RINGLOW			0x228
#define	BGMAC_REG_DMA_RX_RINGHIGH			0x22C
#define	BGMAC_REG_DMA_RX_STATE				0x230
#define		BGMAC_REG_DMA_RX_STATE_CURDESC		0x00001FFF
#define		BGMAC_REG_DMA_RX_STATE_ST		0xF0000000
#define			BGMAC_REG_DMA_RX_STATE_DISABLED	0
#define			BGMAC_REG_DMA_RX_STATE_ACTIVE	1
#define			BGMAC_REG_DMA_RX_STATE_IDLE	2
#define			BGMAC_REG_DMA_RX_STATE_STOPPED	3
#define			BGMAC_REG_DMA_RX_STATE_SUSPEND	4

#define	BGMAC_REG_DMA_RX_ERROR				0x234
#define		BGMAC_REG_DMA_RX_ERROR_CURDESC		0x0001FFFF
#define		BGMAC_REG_DMA_RX_ERROR_ERRS		0xF0000000
#define			BGMAC_REG_DMA_RX_ERROR_NO	0
#define			BGMAC_REG_DMA_RX_ERROR_ADDRESS	0
#define			BGMAC_REG_DMA_RX_ERROR_OVERFLOW	2
#define			BGMAC_REG_DMA_RX_ERROR_TRANSFER	3
#define			BGMAC_REG_DMA_RX_ERROR_DESCREAD	4
#define			BGMAC_REG_DMA_RX_ERROR_CORE	5

#define	BGMAC_REG_DMA_TX_CTRL				0x200
#define	BGMAC_REG_DMA_TX_INDEX				0x204
#define	BGMAC_REG_DMA_TX_RINGLOW			0x208
#define	BGMAC_REG_DMA_TX_RINGHIGH			0x20C
#define	BGMAC_REG_DMA_TX_STATE				0x210
#define	BGMAC_REG_DMA_TX_ERROR				0x214

/* MIB registers (statistics) */

#define	BGMAC_MIB_TX_BYTES				0x30c
#define	BGMAC_MIB_TX_PCKTS				0x314
#define	BGMAC_MIB_TX_ERR_JABBER_PKTS			0x348	/* Error */
#define	BGMAC_MIB_TX_ERR_OVERSIZE_PKTS			0x34c	/* Error */
#define	BGMAC_MIB_TX_ERR_UNDERRUNS			0x354	/* Error */
#define	BGMAC_MIB_TX_ERR_EXCESSIVE_COLS			0x364	/* Error */
#define	BGMAC_MIB_TX_ERR_LATE_COLS			0x368	/* Error */
#define	BGMAC_MIB_TX_DEFERED				0x36c

#define	BGMAC_MIB_TX_Q0_PKTS				0x37c
#define	BGMAC_MIB_TX_Q0_OCTETS				0x380
#define	BGMAC_MIB_TX_Q0_OCTETS_HIGH			0x384
#define	BGMAC_MIB_TX_Q1_PKTS				0x388
#define	BGMAC_MIB_TX_Q1_OCTETS				0x38c
#define	BGMAC_MIB_TX_Q1_OCTETS_HIGH			0x390
#define	BGMAC_MIB_TX_Q2_PKTS				0x394
#define	BGMAC_MIB_TX_Q2_OCTETS				0x398
#define	BGMAC_MIB_TX_Q2_OCTETS_HIGH			0x39c
#define	BGMAC_MIB_TX_Q3_PKTS				0x3a0
#define	BGMAC_MIB_TX_Q3_OCTETS				0x3a4
#define	BGMAC_MIB_TX_Q3_OCTETS_HIGH			0x3a8

#define BGMAC_MIB_RX_GOOD_BYTES				0x3b0
#define BGMAC_MIB_RX_GOOD_PCKTS				0x3b8
#define	BGMAC_MIB_RX_BYTES				0x3bc
#define	BGMAC_MIB_RX_PCKTS				0x3c4
#define	BGMAC_MIB_RX_BROADCAST_PCKTS			0x3c8
#define	BGMAC_MIB_RX_MULTICAST_PCKTS			0x3cc

#define	BGMAC_MIB_RX_ERR_JABBER_PCKTS			0x3f8	/* Error */
#define	BGMAC_MIB_RX_ERR_OVERSIZE_PCKTS			0x3fc	/* Error */
#define	BGMAC_MIB_RX_ERR_MISSED_PCKTS			0x404	/* Error */
#define	BGMAC_MIB_RX_ERR_CRC_ALIGN			0x408	/* Error */
#define	BGMAC_MIB_RX_ERR_UNDERSIZE			0x40c	/* Error */
#define	BGMAC_MIB_RX_ERR_CRC				0x410	/* Error */
#define	BGMAC_MIB_RX_ERR_ALIGN				0x414	/* Error */
#define	BGMAC_MIB_RX_ERR_SYMBOL				0x418	/* Error */
#define BGMAC_MIB_RX_PAUSE				0x41c
#define BGMAC_MIB_RX_NONPAUSE				0x420

#define	BGMAC_REG_CMD_CFG			0x808
#define		BGMAC_REG_CMD_CFG_BITS		\
	"\020\001Tx\002Rx\005Prom\011NoPause\013HalfDuplex\014Reset\020Loopback"
#define		BGMAC_REG_CMD_CFG_TX		0x00000001	/* Transmit enabled */
#define		BGMAC_REG_CMD_CFG_RX		0x00000002	/* Read enabled */
#define		BGMAC_REG_CMD_CFG_SPEED		0x0000000C	/* Select speed: 10/100/1000 */
#define 	BGMAC_REG_CMD_CFG_PROM		0x00000010	/* Promiscuous mode */
#define		BGMAC_REG_CMD_CFG_PAUSEIGNORE	0x00000100	/* Ignore RX PAUSE frames */
#define		BGMAC_REG_CMD_CFG_HALFDUPLEX	0x00000400	/* Half Duplex flag */
#define 	BGMAC_REG_CMD_CFG_RESET		0x00000800	/* Reset pin */
#define		BGMAC_REG_CMD_CFG_LOOPBACK	0x00008000	/* Loopback mode on MAC level */

#define		BGMAC_REG_CMD_CFG_PAD_ENA	0x00000020
#define		BGMAC_REG_CMD_CFG_TAI		0x00000200
#define		BGMAC_REG_CMD_CFG_CFE		0x00800000
#define		BGMAC_REG_CMD_CFG_RL		0x02000000
#define		BGMAC_REG_CMD_CFG_RED		0x04000000
#define		BGMAC_REG_CMD_CFG_PE		0x08000000
#define		BGMAC_REG_CMD_CFG_PF		0x00000080
#define		BGMAC_REG_CMD_CFG_NLC		0x01000000
#define		BGMAC_REG_CMD_CFG_TPI		0x10000000
#define		BGMAC_REG_CMD_CFG_AT		0x20000000

/* UNKNOWN purpose */
#define	BGMAC_PWR_CTL				0x1e8
#define BGMAC_CLOCK_CONTROL_ST			0x1e0

#define	BGMAC_REG_RX_MAX_LEN			0x814
#define BGMAC_PAUSE_CTL				0xb30

#endif /* _MIPS_BROADCOM_BGMAC_BGMACREG_H_ */
